// <auto-generated />
using EF_Eager_Lazy_Explicit_Loading.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Eager_Lazy_Explicit_Loading.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904121807_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Eager_Lazy_Explicit_Loading.DBModels.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SoftwareEngineerId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareEngineerId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SoftwareEngineerId = 1,
                            Type = "PC"
                        },
                        new
                        {
                            Id = 2,
                            SoftwareEngineerId = 1,
                            Type = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            SoftwareEngineerId = 2,
                            Type = "Mobile"
                        });
                });

            modelBuilder.Entity("EF_Eager_Lazy_Explicit_Loading.DBModels.SoftwareEngineer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoftwareEngineer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Test1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Test2"
                        });
                });

            modelBuilder.Entity("EF_Eager_Lazy_Explicit_Loading.DBModels.Device", b =>
                {
                    b.HasOne("EF_Eager_Lazy_Explicit_Loading.DBModels.SoftwareEngineer", "SoftwareEngineer")
                        .WithMany("Devices")
                        .HasForeignKey("SoftwareEngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareEngineer");
                });

            modelBuilder.Entity("EF_Eager_Lazy_Explicit_Loading.DBModels.SoftwareEngineer", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
