// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationsEntityFramework_AspNetCore.DBContext;

#nullable disable

namespace MigrationsEntityFramework_AspNetCore.Migrations
{
    [DbContext(typeof(EntityFrameworkDBContext))]
    partial class EntityFrameworkDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MigrationsEntityFramework_AspNetCore.DBModels.EntityFrameworkRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int>("SolidId")
                        .HasColumnType("int")
                        .HasColumnName("SolidId");

                    b.HasKey("Id")
                        .HasName("PK_EntityFrameworkRecord");

                    b.HasIndex("SolidId")
                        .IsUnique();

                    b.ToTable("EntityFrameworkRecord", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
